baseurl = "http://blog.mingguilu.com"
title = "Continuous  Delivery"
languageCode = "zh-CN"
duoshuoShortname = "imkind"
copyright = "Copyright (c) 2016 - 2021, MingguiLu; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Minggui Lu"

[indexes]
    tag = "tags"
    topic = "topics"
