baseurl = "https://imkind.github.io/" 
title = "Continuous  Delivery"
languageCode = "en-us"
duoshuoShortname = "imkind"
copyright = "Copyright (c) 2016 - 2022, IMkind; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "IMkind"

[indexes]
    tag = "tags"
    topic = "topics"
