baseurl = "https://mingguilu.github.io/"
title = "Continuous  Delivery"
languageCode = "en-us"
duoshuoShortname = "imkind"
copyright = "Copyright (c) 2016 - 2022, MingguiLu; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "MingguiLu"

[indexes]
    tag = "tags"
    topic = "topics"
